export const  API= "API";
export const API_START="API_START";
export const API_END="API_END";
export const FETCH_ANIMES="FETCH_ANIMES"
export const FETCH_ANIMES_REQUESTED="FETCH_ANIMES_REQUESTED"
export const FETCH_ANIMES_SUCCEEDED="FETCH_ANIMES_SUCCEEDED"
export const FETCH_ANIMES_FAILED="FETCH_ANIMES_FAILED"